/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { SDKError } from "./sdkerror.js";

export type BackendSrcAddressValidationResponsesValidationErrorResponseData = {
  detail: Array<models.BackendSrcAddressValidationResponsesValidationErrorItem>;
};

export class BackendSrcAddressValidationResponsesValidationErrorResponse
  extends SDKError
{
  detail: Array<models.BackendSrcAddressValidationResponsesValidationErrorItem>;

  /** The original data that was passed to this error instance. */
  data$: BackendSrcAddressValidationResponsesValidationErrorResponseData;

  constructor(
    err: BackendSrcAddressValidationResponsesValidationErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.detail = err.detail;

    this.name = "BackendSrcAddressValidationResponsesValidationErrorResponse";
  }
}

/** @internal */
export const BackendSrcAddressValidationResponsesValidationErrorResponse$inboundSchema:
  z.ZodType<
    BackendSrcAddressValidationResponsesValidationErrorResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    detail: z.array(
      models
        .BackendSrcAddressValidationResponsesValidationErrorItem$inboundSchema,
    ),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new BackendSrcAddressValidationResponsesValidationErrorResponse(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type BackendSrcAddressValidationResponsesValidationErrorResponse$Outbound =
  {
    detail: Array<
      models.BackendSrcAddressValidationResponsesValidationErrorItem$Outbound
    >;
  };

/** @internal */
export const BackendSrcAddressValidationResponsesValidationErrorResponse$outboundSchema:
  z.ZodType<
    BackendSrcAddressValidationResponsesValidationErrorResponse$Outbound,
    z.ZodTypeDef,
    BackendSrcAddressValidationResponsesValidationErrorResponse
  > = z.instanceof(BackendSrcAddressValidationResponsesValidationErrorResponse)
    .transform(v => v.data$)
    .pipe(z.object({
      detail: z.array(
        models
          .BackendSrcAddressValidationResponsesValidationErrorItem$outboundSchema,
      ),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BackendSrcAddressValidationResponsesValidationErrorResponse$ {
  /** @deprecated use `BackendSrcAddressValidationResponsesValidationErrorResponse$inboundSchema` instead. */
  export const inboundSchema =
    BackendSrcAddressValidationResponsesValidationErrorResponse$inboundSchema;
  /** @deprecated use `BackendSrcAddressValidationResponsesValidationErrorResponse$outboundSchema` instead. */
  export const outboundSchema =
    BackendSrcAddressValidationResponsesValidationErrorResponse$outboundSchema;
  /** @deprecated use `BackendSrcAddressValidationResponsesValidationErrorResponse$Outbound` instead. */
  export type Outbound =
    BackendSrcAddressValidationResponsesValidationErrorResponse$Outbound;
}
