/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { SDKError } from "./sdkerror.js";

export type BackendSrcProductsResponsesValidationErrorResponseData = {
  detail: Array<models.BackendSrcProductsResponsesValidationErrorItem>;
};

export class BackendSrcProductsResponsesValidationErrorResponse
  extends SDKError
{
  detail: Array<models.BackendSrcProductsResponsesValidationErrorItem>;

  /** The original data that was passed to this error instance. */
  data$: BackendSrcProductsResponsesValidationErrorResponseData;

  constructor(
    err: BackendSrcProductsResponsesValidationErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.detail = err.detail;

    this.name = "BackendSrcProductsResponsesValidationErrorResponse";
  }
}

/** @internal */
export const BackendSrcProductsResponsesValidationErrorResponse$inboundSchema:
  z.ZodType<
    BackendSrcProductsResponsesValidationErrorResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    detail: z.array(
      models.BackendSrcProductsResponsesValidationErrorItem$inboundSchema,
    ),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new BackendSrcProductsResponsesValidationErrorResponse(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type BackendSrcProductsResponsesValidationErrorResponse$Outbound = {
  detail: Array<models.BackendSrcProductsResponsesValidationErrorItem$Outbound>;
};

/** @internal */
export const BackendSrcProductsResponsesValidationErrorResponse$outboundSchema:
  z.ZodType<
    BackendSrcProductsResponsesValidationErrorResponse$Outbound,
    z.ZodTypeDef,
    BackendSrcProductsResponsesValidationErrorResponse
  > = z.instanceof(BackendSrcProductsResponsesValidationErrorResponse)
    .transform(v => v.data$)
    .pipe(z.object({
      detail: z.array(
        models.BackendSrcProductsResponsesValidationErrorItem$outboundSchema,
      ),
    }));
