/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetTransactions } from "../../funcs/customersGetTransactions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest$inboundSchema,
};

export const tool$customersGetTransactions: ToolDefinition<typeof args> = {
  name: "customers-get-transactions",
  description: `Get Transactions By Customer Id

Get a list of transactions for a customer by their unique ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersGetTransactions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
