/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exemptionsUploadCertificate } from "../../funcs/exemptionsUploadCertificate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$inboundSchema,
};

export const tool$exemptionsUploadCertificate: ToolDefinition<typeof args> = {
  name: "exemptions-upload-certificate",
  description: `Upload Exemption Certificate

The Upload Exemption Certificate API allows you
    to upload a file attachment (e.g., exemption certificate) for a specific exemption.
    This is primarily used to associate supporting documents with an exemption record
    to ensure compliance and facilitate verification.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exemptionsUploadCertificate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
