/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exemptionsGetExemptionsV1ExemptionsGet } from "../../funcs/exemptionsGetExemptionsV1ExemptionsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetExemptionsV1ExemptionsGetRequest$inboundSchema
    .optional(),
};

export const tool$exemptionsGetExemptionsV1ExemptionsGet: ToolDefinition<
  typeof args
> = {
  name: "exemptions-get-exemptions-v1-exemptions-get",
  description: `Get Exemptions

Retrieve a list of exemptions based on filters.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exemptionsGetExemptionsV1ExemptionsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
