/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exemptionsGet } from "../../funcs/exemptionsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.GetExemptionByIdV1ExemptionsExemptionIdGetRequest$inboundSchema,
};

export const tool$exemptionsGet: ToolDefinition<typeof args> = {
  name: "exemptions-get",
  description: `Get Exemption By Id

The Get Exemption By ID API retrieves a specific exemption record by
    its unique ID. This API is useful for retrieving detailed information
    about a particular exemption, including its associated
    customer, organisation id, status, etc.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exemptionsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
