/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filingsGetByRegistrationId } from "../../funcs/filingsGetByRegistrationId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .GetFilingsByRegistrationIdV1FilingsRegistrationRegistrationIdGetRequest$inboundSchema,
};

export const tool$filingsGetByRegistrationId: ToolDefinition<typeof args> = {
  name: "filings-get-by-registration-id",
  description: `Get Filings By Registration Id

The Get Filings By Registration ID API
    retrieves all filings
    associated with a specific registration ID. This allows users to query detailed
    filing information tied to
    a specific registration record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filingsGetByRegistrationId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
