/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nexusDeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdDelete } from "../../funcs/nexusDeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .DeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdDeleteRequest$inboundSchema,
};

export const tool$nexusDeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdDelete:
  ToolDefinition<typeof args> = {
    name:
      "nexus-delete-physical-nexus-v1-nexus-physical-nexus-physical-nexus-id-delete",
    description: `Delete Physical Nexus

The Delete Physical Nexus API allows you to remove an existing
    physical nexus by its unique ID.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await nexusDeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdDelete(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
