/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsListCategories } from "../../funcs/productsListCategories.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$productsListCategories: ToolDefinition = {
  name: "products-list-categories",
  description: `Get Product Categories

The Get Product Categories API retrieves all
    product categories.  This endpoint helps users understand and select the
    appropriate categories for their products.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await productsListCategories(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
