/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsGetProductCategoriesV1ProductsCategoriesGet } from "../../funcs/productsGetProductCategoriesV1ProductsCategoriesGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$productsGetProductCategoriesV1ProductsCategoriesGet:
  ToolDefinition = {
    name: "products-get-product-categories-v1-products-categories-get",
    description: `Get Product Categories

The Get Product Categories API retrieves all
    product categories.  This endpoint helps users understand and select the
    appropriate categories for their products.`,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await productsGetProductCategoriesV1ProductsCategoriesGet(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
