/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet } from "../../funcs/registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest$inboundSchema,
};

export const tool$registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet:
  ToolDefinition<typeof args> = {
    name:
      "registrations-get-registration-by-id-v1-registrations-registration-id-get",
    description: `Get Registration By Id

The Get Registration By ID API retrieves a single registration record
    based on its unique identifier.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
