/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut } from "../../funcs/registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .UpdateRegistrationV1RegistrationsRegistrationIdPutRequest$inboundSchema,
};

export const tool$registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut:
  ToolDefinition<typeof args> = {
    name:
      "registrations-update-registration-v1-registrations-registration-id-put",
    description: `Update Registration

The Update Registration API allows you to modify
    an existing registration using its unique registration_id.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
