/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost } from "../../funcs/registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .DeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPostRequest$inboundSchema,
};

export const tool$registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost:
  ToolDefinition<typeof args> = {
    name:
      "registrations-deregister-registration-v1-registrations-registration-id-deregister-post",
    description: `Deregister Registration

Deregister an existing registration.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
