/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registrationsGetRegistrationsV1RegistrationsGet } from "../../funcs/registrationsGetRegistrationsV1RegistrationsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetRegistrationsV1RegistrationsGetRequest$inboundSchema
    .optional(),
};

export const tool$registrationsGetRegistrationsV1RegistrationsGet:
  ToolDefinition<typeof args> = {
    name: "registrations-get-registrations-v1-registrations-get",
    description: `Get Registrations

The Get Registrations API retrieves a
    paginated list of registrations.
    This API helps in tracking and managing registrations efficiently across multiple
    jurisdictions.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await registrationsGetRegistrationsV1RegistrationsGet(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
