/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxEstimationEstimate } from "../../funcs/taxEstimationEstimate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EstimateTaxV1TaxEstimatePostRequest$inboundSchema,
};

export const tool$taxEstimationEstimate: ToolDefinition<typeof args> = {
  name: "tax-estimation-estimate",
  description: `Estimate Tax

The Estimate Tax API calculates the estimated tax for a specific
    transaction based on the provided details, including organization nexus,
    transaction details, customer details, and addresses. Optionally simulates nexus being met for tax calculation purposes. The \`simulate_nexus_met\` parameter is deprecated and will be removed in future releases.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await taxEstimationEstimate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
