/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsList } from "../../funcs/transactionsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTransactionsV1TransactionsGetRequest$inboundSchema
    .optional(),
};

export const tool$transactionsList: ToolDefinition<typeof args> = {
  name: "transactions-list",
  description: `Get Transactions

The Get Transactions API retrieves a list of transactions with
    optional filtering, sorting, and pagination.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
