/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsGetById } from "../../funcs/transactionsGetById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .GetTransactionByIdV1TransactionsTransactionIdGetRequest$inboundSchema,
};

export const tool$transactionsGetById: ToolDefinition<typeof args> = {
  name: "transactions-get-by-id",
  description: `Get Transaction By Id

The Get Transaction By Id API retrieves detailed information
    about a specific transaction by providing its unique transaction ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
