/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsPOSTCreateCreditNoteByTransactionId } from "../../funcs/transactionsPOSTCreateCreditNoteByTransactionId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.POSTCreateCreditNoteByTransactionIdRequest$inboundSchema,
};

export const tool$transactionsPOSTCreateCreditNoteByTransactionId:
  ToolDefinition<typeof args> = {
    name: "transactions-POST-create-credit-note-by-transaction-id",
    description: `Create Credit Note By Transaction Id

Create a new credit note for a specific transaction.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await transactionsPOSTCreateCreditNoteByTransactionId(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
