/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsCreateTransactionV1TransactionsPost } from "../../funcs/transactionsCreateTransactionV1TransactionsPost.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.TransactionPublicRequest$inboundSchema,
};

export const tool$transactionsCreateTransactionV1TransactionsPost:
  ToolDefinition<typeof args> = {
    name: "transactions-create-transaction-v1-transactions-post",
    description: `Create Transaction

Create a transaction.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await transactionsCreateTransactionV1TransactionsPost(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
