/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKError } from "../models/errors/sdkerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get Transactions
 *
 * @remarks
 * The Get Transactions API retrieves a list of transactions with
 *     optional filtering, sorting, and pagination.
 */
export function transactionsGet(
  client: SDKCore,
  request?: operations.GetTransactionsV1TransactionsGetRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.PageTransactionRead,
    | errors.ErrorResponse
    | errors.BackendSrcTransactionsResponsesValidationErrorResponse
    | SDKError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: SDKCore,
  request?: operations.GetTransactionsV1TransactionsGetRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      models.PageTransactionRead,
      | errors.ErrorResponse
      | errors.BackendSrcTransactionsResponsesValidationErrorResponse
      | SDKError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      operations.GetTransactionsV1TransactionsGetRequest$outboundSchema
        .optional().parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const path = pathToFunc("/v1/transactions")();

  const query = encodeFormQuery({
    "address_status__in": payload?.address_status__in,
    "country": payload?.country,
    "date__gte": payload?.date__gte,
    "date__lte": payload?.date__lte,
    "exempt__in": payload?.exempt__in,
    "filing_id": payload?.filing_id,
    "marketplace": payload?.marketplace,
    "order_by": payload?.order_by,
    "page": payload?.page,
    "processing_status__in": payload?.processing_status__in,
    "search_query": payload?.search_query,
    "size": payload?.size,
    "state": payload?.state,
    "state_code": payload?.state_code,
    "status": payload?.status,
    "transaction_source": payload?.transaction_source,
    "transaction_type": payload?.transaction_type,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "get_transactions_v1_transactions_get",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "404", "422", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    models.PageTransactionRead,
    | errors.ErrorResponse
    | errors.BackendSrcTransactionsResponsesValidationErrorResponse
    | SDKError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, models.PageTransactionRead$inboundSchema),
    M.jsonErr([401, 404], errors.ErrorResponse$inboundSchema),
    M.jsonErr(
      422,
      errors
        .BackendSrcTransactionsResponsesValidationErrorResponse$inboundSchema,
    ),
    M.jsonErr(500, errors.ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
