/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

<<<<<<< HEAD
import { filingsGet } from "../funcs/filingsGet.js";
import { filingsGetByRegistrationId } from "../funcs/filingsGetByRegistrationId.js";
import { filingsList } from "../funcs/filingsList.js";
=======
import { filingsGetFilingByIdV1FilingsFilingIdGet } from "../funcs/filingsGetFilingByIdV1FilingsFilingIdGet.js";
import { filingsGetFilingsByRegistrationIdV1FilingsRegistrationRegistrationIdGet } from "../funcs/filingsGetFilingsByRegistrationIdV1FilingsRegistrationRegistrationIdGet.js";
import { filingsGetFilingsV1FilingsGet } from "../funcs/filingsGetFilingsV1FilingsGet.js";
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Filings extends ClientSDK {
  /**
   * Get Filings
   *
   * @remarks
   * The Get Filings API retrieves a paginated list of filings based on
   *     filters such as dates, jurisdiction, Country, status, etc. This helps track
   *     and manage tax filings efficiently across multiple jurisdictions.
   */
<<<<<<< HEAD
  async list(
    request?: operations.GetFilingsV1FilingsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PageFilingRead> {
    return unwrapAsync(filingsList(
=======
  async getFilingsV1FilingsGet(
    request?: operations.GetFilingsV1FilingsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PageFilingRead> {
    return unwrapAsync(filingsGetFilingsV1FilingsGet(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
      this,
      request,
      options,
    ));
  }

  /**
   * Get Filing By Id
   *
   * @remarks
   * This API retrieves detailed information about a specific
   *     filing using its unique identifier (filing_id).
   */
<<<<<<< HEAD
  async get(
    request: operations.GetFilingByIdV1FilingsFilingIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.FilingDetailsRead> {
    return unwrapAsync(filingsGet(
=======
  async getFilingByIdV1FilingsFilingIdGet(
    request: operations.GetFilingByIdV1FilingsFilingIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.FilingDetailsRead> {
    return unwrapAsync(filingsGetFilingByIdV1FilingsFilingIdGet(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
      this,
      request,
      options,
    ));
  }

  /**
   * Get Filings By Registration Id
   *
   * @remarks
   * The Get Filings By Registration ID API
   *     retrieves all filings
   *     associated with a specific registration ID. This allows users to query detailed
   *     filing information tied to
   *     a specific registration record.
   */
<<<<<<< HEAD
  async getByRegistrationId(
=======
  async getFilingsByRegistrationIdV1FilingsRegistrationRegistrationIdGet(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
    request:
      operations.GetFilingsByRegistrationIdV1FilingsRegistrationRegistrationIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.PageFilingRead> {
<<<<<<< HEAD
    return unwrapAsync(filingsGetByRegistrationId(
      this,
      request,
      options,
    ));
=======
    return unwrapAsync(
      filingsGetFilingsByRegistrationIdV1FilingsRegistrationRegistrationIdGet(
        this,
        request,
        options,
      ),
    );
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
  }
}
