/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nexusList } from "../funcs/nexusList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Nexus extends ClientSDK {
  /**
   * Get Nexus For Org
   *
   * @remarks
   * Get a list of all nexuses for the organization.
   */
  async list(
    security: operations.GetNexusForOrgV1NexusGetSecurity,
    request: operations.GetNexusForOrgV1NexusGetRequest,
    options?: RequestOptions,
  ): Promise<models.PageNexusResponse> {
    return unwrapAsync(nexusList(
      this,
      security,
      request,
      options,
    ));
  }
}
