/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

<<<<<<< HEAD
import { registrationsCreate } from "../funcs/registrationsCreate.js";
import { registrationsDeregister } from "../funcs/registrationsDeregister.js";
import { registrationsGet } from "../funcs/registrationsGet.js";
import { registrationsGetById } from "../funcs/registrationsGetById.js";
import { registrationsUpdate } from "../funcs/registrationsUpdate.js";
=======
import { registrationsCreateRegistrationV1RegistrationsPost } from "../funcs/registrationsCreateRegistrationV1RegistrationsPost.js";
import { registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost } from "../funcs/registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost.js";
import { registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet } from "../funcs/registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet.js";
import { registrationsGetRegistrationsV1RegistrationsGet } from "../funcs/registrationsGetRegistrationsV1RegistrationsGet.js";
import { registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut } from "../funcs/registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut.js";
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Registrations extends ClientSDK {
  /**
   * Get Registrations
   *
   * @remarks
   * The Get Registrations API retrieves a
   *     paginated list of registrations.
   *     This API helps in tracking and managing registrations efficiently across multiple
   *     jurisdictions.
   */
<<<<<<< HEAD
  async get(
    request?: operations.GetRegistrationsV1RegistrationsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PageRegistrationReadWithPassword> {
    return unwrapAsync(registrationsGet(
=======
  async getRegistrationsV1RegistrationsGet(
    request?: operations.GetRegistrationsV1RegistrationsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PageRegistrationReadWithPassword> {
    return unwrapAsync(registrationsGetRegistrationsV1RegistrationsGet(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
      this,
      request,
      options,
    ));
  }

  /**
   * Create Registration
   *
   * @remarks
   * The Create Registration API allows users to create a new registration
   *     for tracking and managing tax filings efficiently across multiple jurisdictions.
   */
<<<<<<< HEAD
  async create(
    request: operations.CreateRegistration,
    options?: RequestOptions,
  ): Promise<models.RegistrationRead> {
    return unwrapAsync(registrationsCreate(
=======
  async createRegistrationV1RegistrationsPost(
    request: operations.CreateRegistration,
    options?: RequestOptions,
  ): Promise<models.RegistrationRead> {
    return unwrapAsync(registrationsCreateRegistrationV1RegistrationsPost(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
      this,
      request,
      options,
    ));
  }

  /**
   * Get Registration By Id
   *
   * @remarks
   * The Get Registration By ID API retrieves a single registration record
   *     based on its unique identifier.
   */
<<<<<<< HEAD
  async getById(
=======
  async getRegistrationByIdV1RegistrationsRegistrationIdGet(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
    request:
      operations.GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.RegistrationRead> {
<<<<<<< HEAD
    return unwrapAsync(registrationsGetById(
      this,
      request,
      options,
    ));
=======
    return unwrapAsync(
      registrationsGetRegistrationByIdV1RegistrationsRegistrationIdGet(
        this,
        request,
        options,
      ),
    );
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
  }

  /**
   * Update Registration
   *
   * @remarks
   * The Update Registration API allows you to modify
   *     an existing registration using its unique registration_id.
   */
<<<<<<< HEAD
  async update(
=======
  async updateRegistrationV1RegistrationsRegistrationIdPut(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
    request:
      operations.UpdateRegistrationV1RegistrationsRegistrationIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.RegistrationRead> {
<<<<<<< HEAD
    return unwrapAsync(registrationsUpdate(
      this,
      request,
      options,
    ));
=======
    return unwrapAsync(
      registrationsUpdateRegistrationV1RegistrationsRegistrationIdPut(
        this,
        request,
        options,
      ),
    );
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
  }

  /**
   * Deregister Registration
   *
   * @remarks
   * Deregister an existing registration.
   */
<<<<<<< HEAD
  async deregister(
=======
  async deregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost(
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
    request:
      operations.DeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPostRequest,
    options?: RequestOptions,
  ): Promise<models.RegistrationRead> {
<<<<<<< HEAD
    return unwrapAsync(registrationsDeregister(
      this,
      request,
      options,
    ));
=======
    return unwrapAsync(
      registrationsDeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPost(
        this,
        request,
        options,
      ),
    );
>>>>>>> 68f5712d768e774ab185da2f28d4e8cecdd8bee7
  }
}
