/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @kintsugi-tax/tax-platform-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx addressValidationSearch.ts
 */

import { SDK } from "@kintsugi-tax/tax-platform-sdk";

const sdk = new SDK();

async function main() {
  const result = await sdk.search({
    apiKeyHeader: "<YOUR_API_KEY_HERE>",
  }, {
    phone: "555-123-4567",
    street1: "1600 Amphitheatre Parkway",
    street2: "Building 40",
    city: "Mountain View",
    county: "Santa Clara",
    state: "CA",
    postalCode: "94043",
    country: "US",
    fullAddress: "1600 Amphitheatre Parkway, Mountain View, CA 94043",
  });

  console.log(result);
}

main().catch(console.error);
