workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    kintsugi-overlay:
        inputs:
            - location: https://api-doc.trykintsugi.com/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay-1.yaml
        output: output.yaml
        registry:
            location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay
targets:
    typescript:
        target: typescript
        source: kintsugi-overlay
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
