/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFilingByIdV1FilingsFilingIdGetRequest = {
  /**
   * Unique identifier for the filing to retrieve.
   */
  filingId: string;
};

/** @internal */
export const GetFilingByIdV1FilingsFilingIdGetRequest$inboundSchema: z.ZodType<
  GetFilingByIdV1FilingsFilingIdGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filing_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "filing_id": "filingId",
  });
});

/** @internal */
export type GetFilingByIdV1FilingsFilingIdGetRequest$Outbound = {
  filing_id: string;
};

/** @internal */
export const GetFilingByIdV1FilingsFilingIdGetRequest$outboundSchema: z.ZodType<
  GetFilingByIdV1FilingsFilingIdGetRequest$Outbound,
  z.ZodTypeDef,
  GetFilingByIdV1FilingsFilingIdGetRequest
> = z.object({
  filingId: z.string(),
}).transform((v) => {
  return remap$(v, {
    filingId: "filing_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFilingByIdV1FilingsFilingIdGetRequest$ {
  /** @deprecated use `GetFilingByIdV1FilingsFilingIdGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetFilingByIdV1FilingsFilingIdGetRequest$inboundSchema;
  /** @deprecated use `GetFilingByIdV1FilingsFilingIdGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetFilingByIdV1FilingsFilingIdGetRequest$outboundSchema;
  /** @deprecated use `GetFilingByIdV1FilingsFilingIdGetRequest$Outbound` instead. */
  export type Outbound = GetFilingByIdV1FilingsFilingIdGetRequest$Outbound;
}

export function getFilingByIdV1FilingsFilingIdGetRequestToJSON(
  getFilingByIdV1FilingsFilingIdGetRequest:
    GetFilingByIdV1FilingsFilingIdGetRequest,
): string {
  return JSON.stringify(
    GetFilingByIdV1FilingsFilingIdGetRequest$outboundSchema.parse(
      getFilingByIdV1FilingsFilingIdGetRequest,
    ),
  );
}

export function getFilingByIdV1FilingsFilingIdGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetFilingByIdV1FilingsFilingIdGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetFilingByIdV1FilingsFilingIdGetRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetFilingByIdV1FilingsFilingIdGetRequest' from JSON`,
  );
}
