/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetTransactionsV1TransactionsGetRequest = {
  /**
   * Filter transactions by state code.
   */
  stateCode?: string | undefined;
  /**
   * Filter by transaction type (e.g., SALE, FULL_CREDIT_NOTE,
   *
   * @remarks
   *         PARTIAL_CREDIT_NOTE, ARCHIVE etc.).
   */
  transactionType?: string | undefined;
  /**
   * Filter transactions based on the source.
   */
  transactionSource?: string | undefined;
  /**
   * Search for transactions using a general query
   *
   * @remarks
   *         (e.g., order ID, customer name).
   */
  searchQuery?: string | undefined;
  /**
   * Filter transactions by country code
   *
   * @remarks
   *         (ISO 3166-1 alpha-2 format, e.g., US).
   */
  country?: Array<models.CountryCodeEnum> | undefined;
  /**
   * Filter by full state name (e.g., California).
   */
  state?: string | undefined;
  /**
   * Filter by address status (e.g., UNVERIFIED, INVALID,
   *
   * @remarks
   *         PARTIALLY_VERIFIED, VERIFIED, UNVERIFIABLE).
   */
  addressStatusIn?: string | undefined;
  /**
   * Filter by transaction status (e.g., PENDING, COMMITTED,
   *
   * @remarks
   *         CANCELLED, FULLY_REFUNDED, PARTIALLY_REFUNDED, ARCHIVED).
   */
  status?: models.TransactionStatusEnum | undefined;
  /**
   * Retrieve transactions linked to a specific filing ID.
   */
  filingId?: string | undefined;
  /**
   * Sort results based on specified fields.
   *
   * @remarks
   *         Prefix with - for descending order (e.g., -date for newest first).
   */
  orderBy?: string | undefined;
  /**
   * Retrieve transactions with a date
   *
   * @remarks
   *         greater than or equal to (YYYY-MM-DD).
   */
  dateGte?: string | undefined;
  /**
   * Retrieve transactions with a date
   *
   * @remarks
   *         less than or equal to (YYYY-MM-DD).
   */
  dateLte?: string | undefined;
  /**
   * Filter transactions based on processing status.
   *
   * @remarks
   *         Multiple values can be passed as a comma-separated list.
   */
  processingStatusIn?: string | undefined;
  /**
   * Filter transactions by marketplace (e.g., AMAZON, EBAY).
   */
  marketplace?: boolean | undefined;
  /**
   * Filter transactions by exemption status.
   *
   * @remarks
   *         Multiple values can be passed as a comma-separated list (e.g., EXEMPT,TAXABLE).
   */
  exemptIn?: string | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Page size
   */
  size?: number | undefined;
};

/** @internal */
export const GetTransactionsV1TransactionsGetRequest$inboundSchema: z.ZodType<
  GetTransactionsV1TransactionsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  state_code: z.string().optional(),
  transaction_type: z.string().optional(),
  transaction_source: z.string().optional(),
  search_query: z.string().optional(),
  country: z.array(models.CountryCodeEnum$inboundSchema).optional(),
  state: z.string().optional(),
  address_status__in: z.string().default(
    "UNVERIFIED,INVALID,PARTIALLY_VERIFIED,VERIFIED,UNVERIFIABLE",
  ),
  status: models.TransactionStatusEnum$inboundSchema.optional(),
  filing_id: z.string().optional(),
  order_by: z.string().default("date,state,customer_name,status"),
  date__gte: z.string().optional(),
  date__lte: z.string().optional(),
  processing_status__in: z.string().optional(),
  marketplace: z.boolean().optional(),
  exempt__in: z.string().optional(),
  page: z.number().int().default(1),
  size: z.number().int().default(50),
}).transform((v) => {
  return remap$(v, {
    "state_code": "stateCode",
    "transaction_type": "transactionType",
    "transaction_source": "transactionSource",
    "search_query": "searchQuery",
    "address_status__in": "addressStatusIn",
    "filing_id": "filingId",
    "order_by": "orderBy",
    "date__gte": "dateGte",
    "date__lte": "dateLte",
    "processing_status__in": "processingStatusIn",
    "exempt__in": "exemptIn",
  });
});

/** @internal */
export type GetTransactionsV1TransactionsGetRequest$Outbound = {
  state_code?: string | undefined;
  transaction_type?: string | undefined;
  transaction_source?: string | undefined;
  search_query?: string | undefined;
  country?: Array<string> | undefined;
  state?: string | undefined;
  address_status__in: string;
  status?: string | undefined;
  filing_id?: string | undefined;
  order_by: string;
  date__gte?: string | undefined;
  date__lte?: string | undefined;
  processing_status__in?: string | undefined;
  marketplace?: boolean | undefined;
  exempt__in?: string | undefined;
  page: number;
  size: number;
};

/** @internal */
export const GetTransactionsV1TransactionsGetRequest$outboundSchema: z.ZodType<
  GetTransactionsV1TransactionsGetRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionsV1TransactionsGetRequest
> = z.object({
  stateCode: z.string().optional(),
  transactionType: z.string().optional(),
  transactionSource: z.string().optional(),
  searchQuery: z.string().optional(),
  country: z.array(models.CountryCodeEnum$outboundSchema).optional(),
  state: z.string().optional(),
  addressStatusIn: z.string().default(
    "UNVERIFIED,INVALID,PARTIALLY_VERIFIED,VERIFIED,UNVERIFIABLE",
  ),
  status: models.TransactionStatusEnum$outboundSchema.optional(),
  filingId: z.string().optional(),
  orderBy: z.string().default("date,state,customer_name,status"),
  dateGte: z.string().optional(),
  dateLte: z.string().optional(),
  processingStatusIn: z.string().optional(),
  marketplace: z.boolean().optional(),
  exemptIn: z.string().optional(),
  page: z.number().int().default(1),
  size: z.number().int().default(50),
}).transform((v) => {
  return remap$(v, {
    stateCode: "state_code",
    transactionType: "transaction_type",
    transactionSource: "transaction_source",
    searchQuery: "search_query",
    addressStatusIn: "address_status__in",
    filingId: "filing_id",
    orderBy: "order_by",
    dateGte: "date__gte",
    dateLte: "date__lte",
    processingStatusIn: "processing_status__in",
    exemptIn: "exempt__in",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsV1TransactionsGetRequest$ {
  /** @deprecated use `GetTransactionsV1TransactionsGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetTransactionsV1TransactionsGetRequest$inboundSchema;
  /** @deprecated use `GetTransactionsV1TransactionsGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetTransactionsV1TransactionsGetRequest$outboundSchema;
  /** @deprecated use `GetTransactionsV1TransactionsGetRequest$Outbound` instead. */
  export type Outbound = GetTransactionsV1TransactionsGetRequest$Outbound;
}

export function getTransactionsV1TransactionsGetRequestToJSON(
  getTransactionsV1TransactionsGetRequest:
    GetTransactionsV1TransactionsGetRequest,
): string {
  return JSON.stringify(
    GetTransactionsV1TransactionsGetRequest$outboundSchema.parse(
      getTransactionsV1TransactionsGetRequest,
    ),
  );
}

export function getTransactionsV1TransactionsGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetTransactionsV1TransactionsGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetTransactionsV1TransactionsGetRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetTransactionsV1TransactionsGetRequest' from JSON`,
  );
}
