/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest = {
  /**
   * The unique identifier of the filing
   *
   * @remarks
   *         whose transactions you wish to retrieve.
   */
  filingId: string;
};

/** @internal */
export const GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest$inboundSchema:
  z.ZodType<
    GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    filing_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "filing_id": "filingId",
    });
  });
/** @internal */
export type GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest$Outbound =
  {
    filing_id: string;
  };

/** @internal */
export const GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest$outboundSchema:
  z.ZodType<
    GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest
  > = z.object({
    filingId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      filingId: "filing_id",
    });
  });

export function getTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequestToJSON(
  getTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest:
    GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest,
): string {
  return JSON.stringify(
    GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest$outboundSchema
      .parse(getTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest),
  );
}
export function getTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsByFilingIdV1TransactionsFilingsFilingIdGetRequest' from JSON`,
  );
}
