/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type POSTCreateCreditNoteByTransactionIdSecurity = {
  apiKeyHeader?: string | undefined;
  httpBearer?: string | undefined;
};

export type POSTCreateCreditNoteByTransactionIdRequest = {
  originalTransactionId: string;
  /**
   * The unique identifier for the organization making the request
   */
  xOrganizationId: string | null;
  creditNoteCreate: models.CreditNoteCreate;
};

/** @internal */
export const POSTCreateCreditNoteByTransactionIdSecurity$inboundSchema:
  z.ZodType<
    POSTCreateCreditNoteByTransactionIdSecurity,
    z.ZodTypeDef,
    unknown
  > = z.object({
    APIKeyHeader: z.string().optional(),
    HTTPBearer: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "APIKeyHeader": "apiKeyHeader",
      "HTTPBearer": "httpBearer",
    });
  });

/** @internal */
export type POSTCreateCreditNoteByTransactionIdSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  HTTPBearer?: string | undefined;
};

/** @internal */
export const POSTCreateCreditNoteByTransactionIdSecurity$outboundSchema:
  z.ZodType<
    POSTCreateCreditNoteByTransactionIdSecurity$Outbound,
    z.ZodTypeDef,
    POSTCreateCreditNoteByTransactionIdSecurity
  > = z.object({
    apiKeyHeader: z.string().optional(),
    httpBearer: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      apiKeyHeader: "APIKeyHeader",
      httpBearer: "HTTPBearer",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace POSTCreateCreditNoteByTransactionIdSecurity$ {
  /** @deprecated use `POSTCreateCreditNoteByTransactionIdSecurity$inboundSchema` instead. */
  export const inboundSchema =
    POSTCreateCreditNoteByTransactionIdSecurity$inboundSchema;
  /** @deprecated use `POSTCreateCreditNoteByTransactionIdSecurity$outboundSchema` instead. */
  export const outboundSchema =
    POSTCreateCreditNoteByTransactionIdSecurity$outboundSchema;
  /** @deprecated use `POSTCreateCreditNoteByTransactionIdSecurity$Outbound` instead. */
  export type Outbound = POSTCreateCreditNoteByTransactionIdSecurity$Outbound;
}

export function postCreateCreditNoteByTransactionIdSecurityToJSON(
  postCreateCreditNoteByTransactionIdSecurity:
    POSTCreateCreditNoteByTransactionIdSecurity,
): string {
  return JSON.stringify(
    POSTCreateCreditNoteByTransactionIdSecurity$outboundSchema.parse(
      postCreateCreditNoteByTransactionIdSecurity,
    ),
  );
}

export function postCreateCreditNoteByTransactionIdSecurityFromJSON(
  jsonString: string,
): SafeParseResult<
  POSTCreateCreditNoteByTransactionIdSecurity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      POSTCreateCreditNoteByTransactionIdSecurity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'POSTCreateCreditNoteByTransactionIdSecurity' from JSON`,
  );
}

/** @internal */
export const POSTCreateCreditNoteByTransactionIdRequest$inboundSchema:
  z.ZodType<POSTCreateCreditNoteByTransactionIdRequest, z.ZodTypeDef, unknown> =
    z.object({
      original_transaction_id: z.string(),
      "x-organization-id": z.nullable(z.string()),
      CreditNoteCreate: models.CreditNoteCreate$inboundSchema,
    }).transform((v) => {
      return remap$(v, {
        "original_transaction_id": "originalTransactionId",
        "x-organization-id": "xOrganizationId",
        "CreditNoteCreate": "creditNoteCreate",
      });
    });

/** @internal */
export type POSTCreateCreditNoteByTransactionIdRequest$Outbound = {
  original_transaction_id: string;
  "x-organization-id": string | null;
  CreditNoteCreate: models.CreditNoteCreate$Outbound;
};

/** @internal */
export const POSTCreateCreditNoteByTransactionIdRequest$outboundSchema:
  z.ZodType<
    POSTCreateCreditNoteByTransactionIdRequest$Outbound,
    z.ZodTypeDef,
    POSTCreateCreditNoteByTransactionIdRequest
  > = z.object({
    originalTransactionId: z.string(),
    xOrganizationId: z.nullable(z.string()),
    creditNoteCreate: models.CreditNoteCreate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      originalTransactionId: "original_transaction_id",
      xOrganizationId: "x-organization-id",
      creditNoteCreate: "CreditNoteCreate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace POSTCreateCreditNoteByTransactionIdRequest$ {
  /** @deprecated use `POSTCreateCreditNoteByTransactionIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    POSTCreateCreditNoteByTransactionIdRequest$inboundSchema;
  /** @deprecated use `POSTCreateCreditNoteByTransactionIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    POSTCreateCreditNoteByTransactionIdRequest$outboundSchema;
  /** @deprecated use `POSTCreateCreditNoteByTransactionIdRequest$Outbound` instead. */
  export type Outbound = POSTCreateCreditNoteByTransactionIdRequest$Outbound;
}

export function postCreateCreditNoteByTransactionIdRequestToJSON(
  postCreateCreditNoteByTransactionIdRequest:
    POSTCreateCreditNoteByTransactionIdRequest,
): string {
  return JSON.stringify(
    POSTCreateCreditNoteByTransactionIdRequest$outboundSchema.parse(
      postCreateCreditNoteByTransactionIdRequest,
    ),
  );
}

export function postCreateCreditNoteByTransactionIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  POSTCreateCreditNoteByTransactionIdRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      POSTCreateCreditNoteByTransactionIdRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'POSTCreateCreditNoteByTransactionIdRequest' from JSON`,
  );
}
