/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PUTUpdateCreditNoteByTransactionIdRequest = {
  originalTransactionId: string;
  creditNoteId: string;
  creditNoteCreate: models.CreditNoteCreate;
};

/** @internal */
export const PUTUpdateCreditNoteByTransactionIdRequest$inboundSchema: z.ZodType<
  PUTUpdateCreditNoteByTransactionIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  original_transaction_id: z.string(),
  credit_note_id: z.string(),
  CreditNoteCreate: models.CreditNoteCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "original_transaction_id": "originalTransactionId",
    "credit_note_id": "creditNoteId",
    "CreditNoteCreate": "creditNoteCreate",
  });
});

/** @internal */
export type PUTUpdateCreditNoteByTransactionIdRequest$Outbound = {
  original_transaction_id: string;
  credit_note_id: string;
  CreditNoteCreate: models.CreditNoteCreate$Outbound;
};

/** @internal */
export const PUTUpdateCreditNoteByTransactionIdRequest$outboundSchema:
  z.ZodType<
    PUTUpdateCreditNoteByTransactionIdRequest$Outbound,
    z.ZodTypeDef,
    PUTUpdateCreditNoteByTransactionIdRequest
  > = z.object({
    originalTransactionId: z.string(),
    creditNoteId: z.string(),
    creditNoteCreate: models.CreditNoteCreate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      originalTransactionId: "original_transaction_id",
      creditNoteId: "credit_note_id",
      creditNoteCreate: "CreditNoteCreate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PUTUpdateCreditNoteByTransactionIdRequest$ {
  /** @deprecated use `PUTUpdateCreditNoteByTransactionIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    PUTUpdateCreditNoteByTransactionIdRequest$inboundSchema;
  /** @deprecated use `PUTUpdateCreditNoteByTransactionIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    PUTUpdateCreditNoteByTransactionIdRequest$outboundSchema;
  /** @deprecated use `PUTUpdateCreditNoteByTransactionIdRequest$Outbound` instead. */
  export type Outbound = PUTUpdateCreditNoteByTransactionIdRequest$Outbound;
}

export function putUpdateCreditNoteByTransactionIdRequestToJSON(
  putUpdateCreditNoteByTransactionIdRequest:
    PUTUpdateCreditNoteByTransactionIdRequest,
): string {
  return JSON.stringify(
    PUTUpdateCreditNoteByTransactionIdRequest$outboundSchema.parse(
      putUpdateCreditNoteByTransactionIdRequest,
    ),
  );
}

export function putUpdateCreditNoteByTransactionIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PUTUpdateCreditNoteByTransactionIdRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PUTUpdateCreditNoteByTransactionIdRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PUTUpdateCreditNoteByTransactionIdRequest' from JSON`,
  );
}
