/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest =
  {
    /**
     * The unique identifier for the exemption to which the attachment will be associated.
     */
    exemptionId: string;
    bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost:
      models.BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost;
  };

/** @internal */
export const UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$inboundSchema:
  z.ZodType<
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    exemption_id: z.string(),
    Body_upload_exemption_certificate_v1_exemptions__exemption_id__attachments_post:
      models
        .BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "exemption_id": "exemptionId",
      "Body_upload_exemption_certificate_v1_exemptions__exemption_id__attachments_post":
        "bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost",
    });
  });

/** @internal */
export type UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$Outbound =
  {
    exemption_id: string;
    Body_upload_exemption_certificate_v1_exemptions__exemption_id__attachments_post:
      models.BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$Outbound;
  };

/** @internal */
export const UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$outboundSchema:
  z.ZodType<
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$Outbound,
    z.ZodTypeDef,
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest
  > = z.object({
    exemptionId: z.string(),
    bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost:
      models
        .BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      exemptionId: "exemption_id",
      bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost:
        "Body_upload_exemption_certificate_v1_exemptions__exemption_id__attachments_post",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$ {
  /** @deprecated use `UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$inboundSchema` instead. */
  export const inboundSchema =
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$inboundSchema;
  /** @deprecated use `UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$outboundSchema` instead. */
  export const outboundSchema =
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$outboundSchema;
  /** @deprecated use `UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$Outbound` instead. */
  export type Outbound =
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$Outbound;
}

export function uploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequestToJSON(
  uploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest:
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest,
): string {
  return JSON.stringify(
    UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$outboundSchema
      .parse(
        uploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest,
      ),
  );
}

export function uploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostRequest' from JSON`,
  );
}
