/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const AddressStatus = {
  Unverified: "UNVERIFIED",
  Invalid: "INVALID",
  PartiallyVerified: "PARTIALLY_VERIFIED",
  Verified: "VERIFIED",
  Unverifiable: "UNVERIFIABLE",
  Blank: "BLANK",
} as const;
export type AddressStatus = ClosedEnum<typeof AddressStatus>;

/** @internal */
export const AddressStatus$inboundSchema: z.ZodNativeEnum<
  typeof AddressStatus
> = z.nativeEnum(AddressStatus);

/** @internal */
export const AddressStatus$outboundSchema: z.ZodNativeEnum<
  typeof AddressStatus
> = AddressStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressStatus$ {
  /** @deprecated use `AddressStatus$inboundSchema` instead. */
  export const inboundSchema = AddressStatus$inboundSchema;
  /** @deprecated use `AddressStatus$outboundSchema` instead. */
  export const outboundSchema = AddressStatus$outboundSchema;
}
