/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AddressStatus,
  AddressStatus$inboundSchema,
  AddressStatus$outboundSchema,
} from "./addressstatus.js";
import {
  AddressType,
  AddressType$inboundSchema,
  AddressType$outboundSchema,
} from "./addresstype.js";
import {
  CountryCodeEnum,
  CountryCodeEnum$inboundSchema,
  CountryCodeEnum$outboundSchema,
} from "./countrycodeenum.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AddressInput = {
  id?: string | undefined;
  /**
   * Timestamp when transaction was created in Kintsugi.
   */
  createdAt?: Date | undefined;
  /**
   * Timestamp when transaction was last updated.
   */
  updatedAt?: Date | null | undefined;
  /**
   * Phone number associated with the address.
   */
  phone?: string | null | undefined;
  /**
   * Primary street address.
   */
  street1?: string | null | undefined;
  /**
   * Additional street address details, such as an apartment or suite number.
   */
  street2?: string | null | undefined;
  /**
   * City where the customer resides.
   */
  city?: string | null | undefined;
  /**
   * County or district of the customer.
   */
  county?: string | null | undefined;
  /**
   * State or province of the customer.
   */
  state?: string | null | undefined;
  /**
   * ZIP or Postal code of the customer.
   */
  postalCode?: string | null | undefined;
  /**
   * Country code in ISO 3166-1 alpha-2 format
   */
  country?: CountryCodeEnum | null | undefined;
  /**
   * Complete address string of the customer, which can be used as an alternative to individual fields.
   */
  fullAddress?: string | null | undefined;
  type: AddressType;
  /**
   * Optional additional enriched data for the address.
   */
  enrichedFields?: string | null | undefined;
  status?: AddressStatus | undefined;
  organizationId?: string | null | undefined;
  transactionId?: string | null | undefined;
};

/** @internal */
export const AddressInput$inboundSchema: z.ZodType<
  AddressInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  phone: z.nullable(z.string()).optional(),
  street_1: z.nullable(z.string()).optional(),
  street_2: z.nullable(z.string()).optional(),
  city: z.nullable(z.string()).optional(),
  county: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  postal_code: z.nullable(z.string()).optional(),
  country: z.nullable(CountryCodeEnum$inboundSchema).optional(),
  full_address: z.nullable(z.string()).optional(),
  type: AddressType$inboundSchema,
  enriched_fields: z.nullable(z.string()).optional(),
  status: AddressStatus$inboundSchema.optional(),
  organization_id: z.nullable(z.string()).optional(),
  transaction_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "street_1": "street1",
    "street_2": "street2",
    "postal_code": "postalCode",
    "full_address": "fullAddress",
    "enriched_fields": "enrichedFields",
    "organization_id": "organizationId",
    "transaction_id": "transactionId",
  });
});

/** @internal */
export type AddressInput$Outbound = {
  id?: string | undefined;
  created_at?: string | undefined;
  updated_at?: string | null | undefined;
  phone?: string | null | undefined;
  street_1?: string | null | undefined;
  street_2?: string | null | undefined;
  city?: string | null | undefined;
  county?: string | null | undefined;
  state?: string | null | undefined;
  postal_code?: string | null | undefined;
  country?: string | null | undefined;
  full_address?: string | null | undefined;
  type: string;
  enriched_fields?: string | null | undefined;
  status?: string | undefined;
  organization_id?: string | null | undefined;
  transaction_id?: string | null | undefined;
};

/** @internal */
export const AddressInput$outboundSchema: z.ZodType<
  AddressInput$Outbound,
  z.ZodTypeDef,
  AddressInput
> = z.object({
  id: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  phone: z.nullable(z.string()).optional(),
  street1: z.nullable(z.string()).optional(),
  street2: z.nullable(z.string()).optional(),
  city: z.nullable(z.string()).optional(),
  county: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  postalCode: z.nullable(z.string()).optional(),
  country: z.nullable(CountryCodeEnum$outboundSchema).optional(),
  fullAddress: z.nullable(z.string()).optional(),
  type: AddressType$outboundSchema,
  enrichedFields: z.nullable(z.string()).optional(),
  status: AddressStatus$outboundSchema.optional(),
  organizationId: z.nullable(z.string()).optional(),
  transactionId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
    street1: "street_1",
    street2: "street_2",
    postalCode: "postal_code",
    fullAddress: "full_address",
    enrichedFields: "enriched_fields",
    organizationId: "organization_id",
    transactionId: "transaction_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressInput$ {
  /** @deprecated use `AddressInput$inboundSchema` instead. */
  export const inboundSchema = AddressInput$inboundSchema;
  /** @deprecated use `AddressInput$outboundSchema` instead. */
  export const outboundSchema = AddressInput$outboundSchema;
  /** @deprecated use `AddressInput$Outbound` instead. */
  export type Outbound = AddressInput$Outbound;
}

export function addressInputToJSON(addressInput: AddressInput): string {
  return JSON.stringify(AddressInput$outboundSchema.parse(addressInput));
}

export function addressInputFromJSON(
  jsonString: string,
): SafeParseResult<AddressInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressInput' from JSON`,
  );
}
