/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const AddressType = {
  BillTo: "BILL_TO",
  ShipTo: "SHIP_TO",
  ShipFrom: "SHIP_FROM",
  BillFrom: "BILL_FROM",
} as const;
export type AddressType = ClosedEnum<typeof AddressType>;

/** @internal */
export const AddressType$inboundSchema: z.ZodNativeEnum<typeof AddressType> = z
  .nativeEnum(AddressType);
/** @internal */
export const AddressType$outboundSchema: z.ZodNativeEnum<typeof AddressType> =
  AddressType$inboundSchema;
