/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AppliedTo = {
  Transaction: "TRANSACTION",
  TransactionItem: "TRANSACTION_ITEM",
} as const;
export type AppliedTo = ClosedEnum<typeof AppliedTo>;

/** @internal */
export const AppliedTo$inboundSchema: z.ZodNativeEnum<typeof AppliedTo> = z
  .nativeEnum(AppliedTo);

/** @internal */
export const AppliedTo$outboundSchema: z.ZodNativeEnum<typeof AppliedTo> =
  AppliedTo$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppliedTo$ {
  /** @deprecated use `AppliedTo$inboundSchema` instead. */
  export const inboundSchema = AppliedTo$inboundSchema;
  /** @deprecated use `AppliedTo$outboundSchema` instead. */
  export const outboundSchema = AppliedTo$outboundSchema;
}
