/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BackendSrcExemptionsResponsesValidationErrorItem = {
  /**
   * Validation issues, such as missing required
   *
   * @remarks
   *                     fields or invalid field values.
   */
  type: string;
  /**
   * Location of error
   */
  loc: Array<string>;
  /**
   * Error message
   */
  msg: string;
  /**
   * Invalid input value
   */
  input?: any | undefined;
  /**
   * Additional context
   */
  ctx: { [k: string]: any };
};

/** @internal */
export const BackendSrcExemptionsResponsesValidationErrorItem$inboundSchema:
  z.ZodType<
    BackendSrcExemptionsResponsesValidationErrorItem,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
    input: z.any().optional(),
    ctx: z.record(z.any()),
  });
/** @internal */
export type BackendSrcExemptionsResponsesValidationErrorItem$Outbound = {
  type: string;
  loc: Array<string>;
  msg: string;
  input?: any | undefined;
  ctx: { [k: string]: any };
};

/** @internal */
export const BackendSrcExemptionsResponsesValidationErrorItem$outboundSchema:
  z.ZodType<
    BackendSrcExemptionsResponsesValidationErrorItem$Outbound,
    z.ZodTypeDef,
    BackendSrcExemptionsResponsesValidationErrorItem
  > = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
    input: z.any().optional(),
    ctx: z.record(z.any()),
  });

export function backendSrcExemptionsResponsesValidationErrorItemToJSON(
  backendSrcExemptionsResponsesValidationErrorItem:
    BackendSrcExemptionsResponsesValidationErrorItem,
): string {
  return JSON.stringify(
    BackendSrcExemptionsResponsesValidationErrorItem$outboundSchema.parse(
      backendSrcExemptionsResponsesValidationErrorItem,
    ),
  );
}
export function backendSrcExemptionsResponsesValidationErrorItemFromJSON(
  jsonString: string,
): SafeParseResult<
  BackendSrcExemptionsResponsesValidationErrorItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BackendSrcExemptionsResponsesValidationErrorItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BackendSrcExemptionsResponsesValidationErrorItem' from JSON`,
  );
}
