/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BackendSrcNexusResponsesValidationErrorItem = {
  /**
   * Validation issues, such as missing required
   *
   * @remarks
   *                     fields or invalid field values.
   */
  type: string;
  /**
   * Location of error
   */
  loc: Array<string>;
  /**
   * Error message
   */
  msg: string;
  /**
   * Invalid input value
   */
  input?: any | undefined;
  /**
   * Additional context
   */
  ctx: { [k: string]: any };
};

/** @internal */
export const BackendSrcNexusResponsesValidationErrorItem$inboundSchema:
  z.ZodType<
    BackendSrcNexusResponsesValidationErrorItem,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
    input: z.any().optional(),
    ctx: z.record(z.any()),
  });

/** @internal */
export type BackendSrcNexusResponsesValidationErrorItem$Outbound = {
  type: string;
  loc: Array<string>;
  msg: string;
  input?: any | undefined;
  ctx: { [k: string]: any };
};

/** @internal */
export const BackendSrcNexusResponsesValidationErrorItem$outboundSchema:
  z.ZodType<
    BackendSrcNexusResponsesValidationErrorItem$Outbound,
    z.ZodTypeDef,
    BackendSrcNexusResponsesValidationErrorItem
  > = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
    input: z.any().optional(),
    ctx: z.record(z.any()),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BackendSrcNexusResponsesValidationErrorItem$ {
  /** @deprecated use `BackendSrcNexusResponsesValidationErrorItem$inboundSchema` instead. */
  export const inboundSchema =
    BackendSrcNexusResponsesValidationErrorItem$inboundSchema;
  /** @deprecated use `BackendSrcNexusResponsesValidationErrorItem$outboundSchema` instead. */
  export const outboundSchema =
    BackendSrcNexusResponsesValidationErrorItem$outboundSchema;
  /** @deprecated use `BackendSrcNexusResponsesValidationErrorItem$Outbound` instead. */
  export type Outbound = BackendSrcNexusResponsesValidationErrorItem$Outbound;
}

export function backendSrcNexusResponsesValidationErrorItemToJSON(
  backendSrcNexusResponsesValidationErrorItem:
    BackendSrcNexusResponsesValidationErrorItem,
): string {
  return JSON.stringify(
    BackendSrcNexusResponsesValidationErrorItem$outboundSchema.parse(
      backendSrcNexusResponsesValidationErrorItem,
    ),
  );
}

export function backendSrcNexusResponsesValidationErrorItemFromJSON(
  jsonString: string,
): SafeParseResult<
  BackendSrcNexusResponsesValidationErrorItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BackendSrcNexusResponsesValidationErrorItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BackendSrcNexusResponsesValidationErrorItem' from JSON`,
  );
}
