/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BackendSrcTransactionsResponsesValidationErrorItem = {
  /**
   * Validation issues, such as missing required
   *
   * @remarks
   *                     fields or invalid field values.
   */
  type: string;
  /**
   * Location of error
   */
  loc: Array<string>;
  /**
   * Error message
   */
  msg: string;
  /**
   * Invalid input value
   */
  input?: any | undefined;
  /**
   * Additional context
   */
  ctx: { [k: string]: any };
};

/** @internal */
export const BackendSrcTransactionsResponsesValidationErrorItem$inboundSchema:
  z.ZodType<
    BackendSrcTransactionsResponsesValidationErrorItem,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
    input: z.any().optional(),
    ctx: z.record(z.any()),
  });

/** @internal */
export type BackendSrcTransactionsResponsesValidationErrorItem$Outbound = {
  type: string;
  loc: Array<string>;
  msg: string;
  input?: any | undefined;
  ctx: { [k: string]: any };
};

/** @internal */
export const BackendSrcTransactionsResponsesValidationErrorItem$outboundSchema:
  z.ZodType<
    BackendSrcTransactionsResponsesValidationErrorItem$Outbound,
    z.ZodTypeDef,
    BackendSrcTransactionsResponsesValidationErrorItem
  > = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
    input: z.any().optional(),
    ctx: z.record(z.any()),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BackendSrcTransactionsResponsesValidationErrorItem$ {
  /** @deprecated use `BackendSrcTransactionsResponsesValidationErrorItem$inboundSchema` instead. */
  export const inboundSchema =
    BackendSrcTransactionsResponsesValidationErrorItem$inboundSchema;
  /** @deprecated use `BackendSrcTransactionsResponsesValidationErrorItem$outboundSchema` instead. */
  export const outboundSchema =
    BackendSrcTransactionsResponsesValidationErrorItem$outboundSchema;
  /** @deprecated use `BackendSrcTransactionsResponsesValidationErrorItem$Outbound` instead. */
  export type Outbound =
    BackendSrcTransactionsResponsesValidationErrorItem$Outbound;
}

export function backendSrcTransactionsResponsesValidationErrorItemToJSON(
  backendSrcTransactionsResponsesValidationErrorItem:
    BackendSrcTransactionsResponsesValidationErrorItem,
): string {
  return JSON.stringify(
    BackendSrcTransactionsResponsesValidationErrorItem$outboundSchema.parse(
      backendSrcTransactionsResponsesValidationErrorItem,
    ),
  );
}

export function backendSrcTransactionsResponsesValidationErrorItemFromJSON(
  jsonString: string,
): SafeParseResult<
  BackendSrcTransactionsResponsesValidationErrorItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BackendSrcTransactionsResponsesValidationErrorItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BackendSrcTransactionsResponsesValidationErrorItem' from JSON`,
  );
}
