/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { blobLikeSchema } from "../types/blobs.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost =
  {
    /**
     * The file to be uploaded. Supported format: PDF. Max size: 10 MB.
     */
    file: FileT | Blob;
  };

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}

/** @internal */
export const BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$inboundSchema:
  z.ZodType<
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost,
    z.ZodTypeDef,
    unknown
  > = z.object({
    file: z.lazy(() => FileT$inboundSchema),
  });

/** @internal */
export type BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$Outbound =
  {
    file: FileT$Outbound | Blob;
  };

/** @internal */
export const BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$outboundSchema:
  z.ZodType<
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$Outbound,
    z.ZodTypeDef,
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost
  > = z.object({
    file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$ {
  /** @deprecated use `BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$inboundSchema` instead. */
  export const inboundSchema =
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$inboundSchema;
  /** @deprecated use `BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$outboundSchema` instead. */
  export const outboundSchema =
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$outboundSchema;
  /** @deprecated use `BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$Outbound` instead. */
  export type Outbound =
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$Outbound;
}

export function bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostToJSON(
  bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost:
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost,
): string {
  return JSON.stringify(
    BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$outboundSchema
      .parse(
        bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost,
      ),
  );
}

export function bodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPostFromJSON(
  jsonString: string,
): SafeParseResult<
  BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'BodyUploadExemptionCertificateV1ExemptionsExemptionIdAttachmentsPost' from JSON`,
  );
}
