/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TaxExemptionEnum,
  TaxExemptionEnum$inboundSchema,
  TaxExemptionEnum$outboundSchema,
} from "./taxexemptionenum.js";
import {
  TaxItemBuilder,
  TaxItemBuilder$inboundSchema,
  TaxItemBuilder$Outbound,
  TaxItemBuilder$outboundSchema,
} from "./taxitembuilder.js";

/**
 * Number of units or amount of the product being credited.
 */
export type CreditNoteItemCreateUpdateQuantity = number | string;

/**
 * Total monetary value of the credit note item before taxes.
 */
export type CreditNoteItemCreateUpdateAmount = number | string;

/**
 * Pre-calculated tax amount for the item, if provided by the external system.
 */
export type CreditNoteItemCreateUpdateTaxAmountImported = number | string;

/**
 * Pre-calculated tax rate for the item, if provided by the external system.
 */
export type CreditNoteItemCreateUpdateTaxRateImported = number | string;

/**
 * Portion of the item amount subject to taxation.
 */
export type CreditNoteItemCreateUpdateTaxableAmount = number | string;

export type CreditNoteItemCreateUpdate = {
  /**
   * Unique identifier for the credit note item in the external system.
   */
  externalId: string;
  /**
   * Date when the credit note item was issued or created.
   */
  date: Date;
  /**
   * Brief explanation or details about the credit note item.
   */
  description?: string | null | undefined;
  /**
   * Unique identifier for the associated product in the external system.
   */
  externalProductId: string;
  /**
   * Number of units or amount of the product being credited.
   */
  quantity?: number | string | undefined;
  /**
   * Total monetary value of the credit note item before taxes.
   */
  amount?: number | string | undefined;
  /**
   * Pre-calculated tax amount for the item, if provided by the external system.
   */
  taxAmountImported?: number | string | null | undefined;
  /**
   * Pre-calculated tax rate for the item, if provided by the external system.
   */
  taxRateImported?: number | string | null | undefined;
  /**
   * Portion of the item amount subject to taxation.
   */
  taxableAmount?: number | string | null | undefined;
  /**
   * Specific tax exemption status applied to this item, if any.
   */
  taxExemption?: TaxExemptionEnum | null | undefined;
  /**
   * Detailed breakdown of individual tax components applied to this item.
   */
  taxItems?: Array<TaxItemBuilder> | undefined;
};

/** @internal */
export const CreditNoteItemCreateUpdateQuantity$inboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateQuantity,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type CreditNoteItemCreateUpdateQuantity$Outbound = number | string;

/** @internal */
export const CreditNoteItemCreateUpdateQuantity$outboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateQuantity$Outbound,
  z.ZodTypeDef,
  CreditNoteItemCreateUpdateQuantity
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreditNoteItemCreateUpdateQuantity$ {
  /** @deprecated use `CreditNoteItemCreateUpdateQuantity$inboundSchema` instead. */
  export const inboundSchema = CreditNoteItemCreateUpdateQuantity$inboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateQuantity$outboundSchema` instead. */
  export const outboundSchema =
    CreditNoteItemCreateUpdateQuantity$outboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateQuantity$Outbound` instead. */
  export type Outbound = CreditNoteItemCreateUpdateQuantity$Outbound;
}

export function creditNoteItemCreateUpdateQuantityToJSON(
  creditNoteItemCreateUpdateQuantity: CreditNoteItemCreateUpdateQuantity,
): string {
  return JSON.stringify(
    CreditNoteItemCreateUpdateQuantity$outboundSchema.parse(
      creditNoteItemCreateUpdateQuantity,
    ),
  );
}

export function creditNoteItemCreateUpdateQuantityFromJSON(
  jsonString: string,
): SafeParseResult<CreditNoteItemCreateUpdateQuantity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreditNoteItemCreateUpdateQuantity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditNoteItemCreateUpdateQuantity' from JSON`,
  );
}

/** @internal */
export const CreditNoteItemCreateUpdateAmount$inboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateAmount,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type CreditNoteItemCreateUpdateAmount$Outbound = number | string;

/** @internal */
export const CreditNoteItemCreateUpdateAmount$outboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateAmount$Outbound,
  z.ZodTypeDef,
  CreditNoteItemCreateUpdateAmount
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreditNoteItemCreateUpdateAmount$ {
  /** @deprecated use `CreditNoteItemCreateUpdateAmount$inboundSchema` instead. */
  export const inboundSchema = CreditNoteItemCreateUpdateAmount$inboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateAmount$outboundSchema` instead. */
  export const outboundSchema = CreditNoteItemCreateUpdateAmount$outboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateAmount$Outbound` instead. */
  export type Outbound = CreditNoteItemCreateUpdateAmount$Outbound;
}

export function creditNoteItemCreateUpdateAmountToJSON(
  creditNoteItemCreateUpdateAmount: CreditNoteItemCreateUpdateAmount,
): string {
  return JSON.stringify(
    CreditNoteItemCreateUpdateAmount$outboundSchema.parse(
      creditNoteItemCreateUpdateAmount,
    ),
  );
}

export function creditNoteItemCreateUpdateAmountFromJSON(
  jsonString: string,
): SafeParseResult<CreditNoteItemCreateUpdateAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditNoteItemCreateUpdateAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditNoteItemCreateUpdateAmount' from JSON`,
  );
}

/** @internal */
export const CreditNoteItemCreateUpdateTaxAmountImported$inboundSchema:
  z.ZodType<
    CreditNoteItemCreateUpdateTaxAmountImported,
    z.ZodTypeDef,
    unknown
  > = z.union([z.number(), z.string()]);

/** @internal */
export type CreditNoteItemCreateUpdateTaxAmountImported$Outbound =
  | number
  | string;

/** @internal */
export const CreditNoteItemCreateUpdateTaxAmountImported$outboundSchema:
  z.ZodType<
    CreditNoteItemCreateUpdateTaxAmountImported$Outbound,
    z.ZodTypeDef,
    CreditNoteItemCreateUpdateTaxAmountImported
  > = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreditNoteItemCreateUpdateTaxAmountImported$ {
  /** @deprecated use `CreditNoteItemCreateUpdateTaxAmountImported$inboundSchema` instead. */
  export const inboundSchema =
    CreditNoteItemCreateUpdateTaxAmountImported$inboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateTaxAmountImported$outboundSchema` instead. */
  export const outboundSchema =
    CreditNoteItemCreateUpdateTaxAmountImported$outboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateTaxAmountImported$Outbound` instead. */
  export type Outbound = CreditNoteItemCreateUpdateTaxAmountImported$Outbound;
}

export function creditNoteItemCreateUpdateTaxAmountImportedToJSON(
  creditNoteItemCreateUpdateTaxAmountImported:
    CreditNoteItemCreateUpdateTaxAmountImported,
): string {
  return JSON.stringify(
    CreditNoteItemCreateUpdateTaxAmountImported$outboundSchema.parse(
      creditNoteItemCreateUpdateTaxAmountImported,
    ),
  );
}

export function creditNoteItemCreateUpdateTaxAmountImportedFromJSON(
  jsonString: string,
): SafeParseResult<
  CreditNoteItemCreateUpdateTaxAmountImported,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreditNoteItemCreateUpdateTaxAmountImported$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreditNoteItemCreateUpdateTaxAmountImported' from JSON`,
  );
}

/** @internal */
export const CreditNoteItemCreateUpdateTaxRateImported$inboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateTaxRateImported,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type CreditNoteItemCreateUpdateTaxRateImported$Outbound =
  | number
  | string;

/** @internal */
export const CreditNoteItemCreateUpdateTaxRateImported$outboundSchema:
  z.ZodType<
    CreditNoteItemCreateUpdateTaxRateImported$Outbound,
    z.ZodTypeDef,
    CreditNoteItemCreateUpdateTaxRateImported
  > = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreditNoteItemCreateUpdateTaxRateImported$ {
  /** @deprecated use `CreditNoteItemCreateUpdateTaxRateImported$inboundSchema` instead. */
  export const inboundSchema =
    CreditNoteItemCreateUpdateTaxRateImported$inboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateTaxRateImported$outboundSchema` instead. */
  export const outboundSchema =
    CreditNoteItemCreateUpdateTaxRateImported$outboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateTaxRateImported$Outbound` instead. */
  export type Outbound = CreditNoteItemCreateUpdateTaxRateImported$Outbound;
}

export function creditNoteItemCreateUpdateTaxRateImportedToJSON(
  creditNoteItemCreateUpdateTaxRateImported:
    CreditNoteItemCreateUpdateTaxRateImported,
): string {
  return JSON.stringify(
    CreditNoteItemCreateUpdateTaxRateImported$outboundSchema.parse(
      creditNoteItemCreateUpdateTaxRateImported,
    ),
  );
}

export function creditNoteItemCreateUpdateTaxRateImportedFromJSON(
  jsonString: string,
): SafeParseResult<
  CreditNoteItemCreateUpdateTaxRateImported,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreditNoteItemCreateUpdateTaxRateImported$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreditNoteItemCreateUpdateTaxRateImported' from JSON`,
  );
}

/** @internal */
export const CreditNoteItemCreateUpdateTaxableAmount$inboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateTaxableAmount,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type CreditNoteItemCreateUpdateTaxableAmount$Outbound = number | string;

/** @internal */
export const CreditNoteItemCreateUpdateTaxableAmount$outboundSchema: z.ZodType<
  CreditNoteItemCreateUpdateTaxableAmount$Outbound,
  z.ZodTypeDef,
  CreditNoteItemCreateUpdateTaxableAmount
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreditNoteItemCreateUpdateTaxableAmount$ {
  /** @deprecated use `CreditNoteItemCreateUpdateTaxableAmount$inboundSchema` instead. */
  export const inboundSchema =
    CreditNoteItemCreateUpdateTaxableAmount$inboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateTaxableAmount$outboundSchema` instead. */
  export const outboundSchema =
    CreditNoteItemCreateUpdateTaxableAmount$outboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdateTaxableAmount$Outbound` instead. */
  export type Outbound = CreditNoteItemCreateUpdateTaxableAmount$Outbound;
}

export function creditNoteItemCreateUpdateTaxableAmountToJSON(
  creditNoteItemCreateUpdateTaxableAmount:
    CreditNoteItemCreateUpdateTaxableAmount,
): string {
  return JSON.stringify(
    CreditNoteItemCreateUpdateTaxableAmount$outboundSchema.parse(
      creditNoteItemCreateUpdateTaxableAmount,
    ),
  );
}

export function creditNoteItemCreateUpdateTaxableAmountFromJSON(
  jsonString: string,
): SafeParseResult<
  CreditNoteItemCreateUpdateTaxableAmount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreditNoteItemCreateUpdateTaxableAmount$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreditNoteItemCreateUpdateTaxableAmount' from JSON`,
  );
}

/** @internal */
export const CreditNoteItemCreateUpdate$inboundSchema: z.ZodType<
  CreditNoteItemCreateUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string(),
  date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  description: z.nullable(z.string()).optional(),
  external_product_id: z.string(),
  quantity: z.union([z.number(), z.string()]).optional(),
  amount: z.union([z.number(), z.string()]).optional(),
  tax_amount_imported: z.nullable(z.union([z.number(), z.string()])).optional(),
  tax_rate_imported: z.nullable(z.union([z.number(), z.string()])).optional(),
  taxable_amount: z.nullable(z.union([z.number(), z.string()])).optional(),
  tax_exemption: z.nullable(TaxExemptionEnum$inboundSchema).optional(),
  tax_items: z.array(TaxItemBuilder$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "external_id": "externalId",
    "external_product_id": "externalProductId",
    "tax_amount_imported": "taxAmountImported",
    "tax_rate_imported": "taxRateImported",
    "taxable_amount": "taxableAmount",
    "tax_exemption": "taxExemption",
    "tax_items": "taxItems",
  });
});

/** @internal */
export type CreditNoteItemCreateUpdate$Outbound = {
  external_id: string;
  date: string;
  description?: string | null | undefined;
  external_product_id: string;
  quantity?: number | string | undefined;
  amount?: number | string | undefined;
  tax_amount_imported?: number | string | null | undefined;
  tax_rate_imported?: number | string | null | undefined;
  taxable_amount?: number | string | null | undefined;
  tax_exemption?: string | null | undefined;
  tax_items?: Array<TaxItemBuilder$Outbound> | undefined;
};

/** @internal */
export const CreditNoteItemCreateUpdate$outboundSchema: z.ZodType<
  CreditNoteItemCreateUpdate$Outbound,
  z.ZodTypeDef,
  CreditNoteItemCreateUpdate
> = z.object({
  externalId: z.string(),
  date: z.date().transform(v => v.toISOString()),
  description: z.nullable(z.string()).optional(),
  externalProductId: z.string(),
  quantity: z.union([z.number(), z.string()]).optional(),
  amount: z.union([z.number(), z.string()]).optional(),
  taxAmountImported: z.nullable(z.union([z.number(), z.string()])).optional(),
  taxRateImported: z.nullable(z.union([z.number(), z.string()])).optional(),
  taxableAmount: z.nullable(z.union([z.number(), z.string()])).optional(),
  taxExemption: z.nullable(TaxExemptionEnum$outboundSchema).optional(),
  taxItems: z.array(TaxItemBuilder$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    externalId: "external_id",
    externalProductId: "external_product_id",
    taxAmountImported: "tax_amount_imported",
    taxRateImported: "tax_rate_imported",
    taxableAmount: "taxable_amount",
    taxExemption: "tax_exemption",
    taxItems: "tax_items",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreditNoteItemCreateUpdate$ {
  /** @deprecated use `CreditNoteItemCreateUpdate$inboundSchema` instead. */
  export const inboundSchema = CreditNoteItemCreateUpdate$inboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdate$outboundSchema` instead. */
  export const outboundSchema = CreditNoteItemCreateUpdate$outboundSchema;
  /** @deprecated use `CreditNoteItemCreateUpdate$Outbound` instead. */
  export type Outbound = CreditNoteItemCreateUpdate$Outbound;
}

export function creditNoteItemCreateUpdateToJSON(
  creditNoteItemCreateUpdate: CreditNoteItemCreateUpdate,
): string {
  return JSON.stringify(
    CreditNoteItemCreateUpdate$outboundSchema.parse(creditNoteItemCreateUpdate),
  );
}

export function creditNoteItemCreateUpdateFromJSON(
  jsonString: string,
): SafeParseResult<CreditNoteItemCreateUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditNoteItemCreateUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditNoteItemCreateUpdate' from JSON`,
  );
}
