/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AddressStatus,
  AddressStatus$inboundSchema,
  AddressStatus$outboundSchema,
} from "./addressstatus.js";
import {
  CountryCodeEnum,
  CountryCodeEnum$inboundSchema,
  CountryCodeEnum$outboundSchema,
} from "./countrycodeenum.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SourceEnum,
  SourceEnum$inboundSchema,
  SourceEnum$outboundSchema,
} from "./sourceenum.js";
import {
  StatusEnum,
  StatusEnum$inboundSchema,
  StatusEnum$outboundSchema,
} from "./statusenum.js";

export type CustomerBaseBase = {
  /**
   * Phone number associated with the address.
   */
  phone?: string | null | undefined;
  /**
   * Primary street address.
   */
  street1?: string | null | undefined;
  /**
   * Additional street address details, such as an apartment or suite number.
   */
  street2?: string | null | undefined;
  /**
   * City where the customer resides.
   */
  city?: string | null | undefined;
  /**
   * County or district of the customer.
   */
  county?: string | null | undefined;
  /**
   * State or province of the customer.
   */
  state?: string | null | undefined;
  /**
   * ZIP or Postal code of the customer.
   */
  postalCode?: string | null | undefined;
  /**
   * Country code in ISO 3166-1 alpha-2 format
   */
  country?: CountryCodeEnum | null | undefined;
  /**
   * Complete address string of the customer, which can be used as an alternative to individual fields.
   */
  fullAddress?: string | null | undefined;
  /**
   * Name of the customer.
   */
  name?: string | null | undefined;
  /**
   * A unique identifier for the customer.
   */
  externalId?: string | null | undefined;
  status?: StatusEnum | undefined;
  /**
   * Email address of the customer.
   */
  email?: string | null | undefined;
  addressStatus?: AddressStatus | undefined;
  /**
   * Source of the customer information (e.g., BIGCOMMERCE, STRIPE, etc.).
   */
  source?: SourceEnum | null | undefined;
  registrationNumber?: string | null | undefined;
  /**
   * Unique identifier of the connection related to the customer.
   */
  connectionId?: string | null | undefined;
  /**
   * Additional enriched fields for the customer, if available.
   */
  enrichedFields?: string | null | undefined;
  organizationId: string;
  isTestData?: boolean | undefined;
};

/** @internal */
export const CustomerBaseBase$inboundSchema: z.ZodType<
  CustomerBaseBase,
  z.ZodTypeDef,
  unknown
> = z.object({
  phone: z.nullable(z.string()).optional(),
  street_1: z.nullable(z.string()).optional(),
  street_2: z.nullable(z.string()).optional(),
  city: z.nullable(z.string()).optional(),
  county: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  postal_code: z.nullable(z.string()).optional(),
  country: z.nullable(CountryCodeEnum$inboundSchema).optional(),
  full_address: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  external_id: z.nullable(z.string()).optional(),
  status: StatusEnum$inboundSchema.optional(),
  email: z.nullable(z.string()).optional(),
  address_status: AddressStatus$inboundSchema.optional(),
  source: z.nullable(SourceEnum$inboundSchema).optional(),
  registration_number: z.nullable(z.string()).optional(),
  connection_id: z.nullable(z.string()).optional(),
  enriched_fields: z.nullable(z.string()).optional(),
  organization_id: z.string(),
  is_test_data: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "street_1": "street1",
    "street_2": "street2",
    "postal_code": "postalCode",
    "full_address": "fullAddress",
    "external_id": "externalId",
    "address_status": "addressStatus",
    "registration_number": "registrationNumber",
    "connection_id": "connectionId",
    "enriched_fields": "enrichedFields",
    "organization_id": "organizationId",
    "is_test_data": "isTestData",
  });
});

/** @internal */
export type CustomerBaseBase$Outbound = {
  phone?: string | null | undefined;
  street_1?: string | null | undefined;
  street_2?: string | null | undefined;
  city?: string | null | undefined;
  county?: string | null | undefined;
  state?: string | null | undefined;
  postal_code?: string | null | undefined;
  country?: string | null | undefined;
  full_address?: string | null | undefined;
  name?: string | null | undefined;
  external_id?: string | null | undefined;
  status?: string | undefined;
  email?: string | null | undefined;
  address_status?: string | undefined;
  source?: string | null | undefined;
  registration_number?: string | null | undefined;
  connection_id?: string | null | undefined;
  enriched_fields?: string | null | undefined;
  organization_id: string;
  is_test_data: boolean;
};

/** @internal */
export const CustomerBaseBase$outboundSchema: z.ZodType<
  CustomerBaseBase$Outbound,
  z.ZodTypeDef,
  CustomerBaseBase
> = z.object({
  phone: z.nullable(z.string()).optional(),
  street1: z.nullable(z.string()).optional(),
  street2: z.nullable(z.string()).optional(),
  city: z.nullable(z.string()).optional(),
  county: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  postalCode: z.nullable(z.string()).optional(),
  country: z.nullable(CountryCodeEnum$outboundSchema).optional(),
  fullAddress: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  externalId: z.nullable(z.string()).optional(),
  status: StatusEnum$outboundSchema.optional(),
  email: z.nullable(z.string()).optional(),
  addressStatus: AddressStatus$outboundSchema.optional(),
  source: z.nullable(SourceEnum$outboundSchema).optional(),
  registrationNumber: z.nullable(z.string()).optional(),
  connectionId: z.nullable(z.string()).optional(),
  enrichedFields: z.nullable(z.string()).optional(),
  organizationId: z.string(),
  isTestData: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    street1: "street_1",
    street2: "street_2",
    postalCode: "postal_code",
    fullAddress: "full_address",
    externalId: "external_id",
    addressStatus: "address_status",
    registrationNumber: "registration_number",
    connectionId: "connection_id",
    enrichedFields: "enriched_fields",
    organizationId: "organization_id",
    isTestData: "is_test_data",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerBaseBase$ {
  /** @deprecated use `CustomerBaseBase$inboundSchema` instead. */
  export const inboundSchema = CustomerBaseBase$inboundSchema;
  /** @deprecated use `CustomerBaseBase$outboundSchema` instead. */
  export const outboundSchema = CustomerBaseBase$outboundSchema;
  /** @deprecated use `CustomerBaseBase$Outbound` instead. */
  export type Outbound = CustomerBaseBase$Outbound;
}

export function customerBaseBaseToJSON(
  customerBaseBase: CustomerBaseBase,
): string {
  return JSON.stringify(
    CustomerBaseBase$outboundSchema.parse(customerBaseBase),
  );
}

export function customerBaseBaseFromJSON(
  jsonString: string,
): SafeParseResult<CustomerBaseBase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerBaseBase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerBaseBase' from JSON`,
  );
}
