/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Enum for customer tax registration types.
 */
export const CustomerTaxTypeEnum = {
  Gst: "gst",
  Hst: "hst",
  GstHst: "gst_hst",
  Qst: "qst",
  Pst: "pst",
  Rst: "rst",
  Vat: "vat",
  Unknown: "unknown",
} as const;
/**
 * Enum for customer tax registration types.
 */
export type CustomerTaxTypeEnum = ClosedEnum<typeof CustomerTaxTypeEnum>;

/** @internal */
export const CustomerTaxTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof CustomerTaxTypeEnum
> = z.nativeEnum(CustomerTaxTypeEnum);

/** @internal */
export const CustomerTaxTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof CustomerTaxTypeEnum
> = CustomerTaxTypeEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerTaxTypeEnum$ {
  /** @deprecated use `CustomerTaxTypeEnum$inboundSchema` instead. */
  export const inboundSchema = CustomerTaxTypeEnum$inboundSchema;
  /** @deprecated use `CustomerTaxTypeEnum$outboundSchema` instead. */
  export const outboundSchema = CustomerTaxTypeEnum$outboundSchema;
}
