/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const ExemptionStatus = {
  Active: "ACTIVE",
  Inactive: "INACTIVE",
  Expired: "EXPIRED",
  Deactivated: "DEACTIVATED",
  Archived: "ARCHIVED",
} as const;
export type ExemptionStatus = ClosedEnum<typeof ExemptionStatus>;

/** @internal */
export const ExemptionStatus$inboundSchema: z.ZodNativeEnum<
  typeof ExemptionStatus
> = z.nativeEnum(ExemptionStatus);
/** @internal */
export const ExemptionStatus$outboundSchema: z.ZodNativeEnum<
  typeof ExemptionStatus
> = ExemptionStatus$inboundSchema;
