/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  BackendSrcExemptionsModelsExemptionRead,
  BackendSrcExemptionsModelsExemptionRead$inboundSchema,
  BackendSrcExemptionsModelsExemptionRead$Outbound,
  BackendSrcExemptionsModelsExemptionRead$outboundSchema,
} from "./backendsrcexemptionsmodelsexemptionread.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FastapiPaginationDefaultPageExemptionRead2 = {
  items: Array<BackendSrcExemptionsModelsExemptionRead>;
  total: number;
  page: number;
  size: number;
  pages: number;
};

/** @internal */
export const FastapiPaginationDefaultPageExemptionRead2$inboundSchema:
  z.ZodType<FastapiPaginationDefaultPageExemptionRead2, z.ZodTypeDef, unknown> =
    z.object({
      items: z.array(BackendSrcExemptionsModelsExemptionRead$inboundSchema),
      total: z.number().int(),
      page: z.number().int(),
      size: z.number().int(),
      pages: z.number().int(),
    });
/** @internal */
export type FastapiPaginationDefaultPageExemptionRead2$Outbound = {
  items: Array<BackendSrcExemptionsModelsExemptionRead$Outbound>;
  total: number;
  page: number;
  size: number;
  pages: number;
};

/** @internal */
export const FastapiPaginationDefaultPageExemptionRead2$outboundSchema:
  z.ZodType<
    FastapiPaginationDefaultPageExemptionRead2$Outbound,
    z.ZodTypeDef,
    FastapiPaginationDefaultPageExemptionRead2
  > = z.object({
    items: z.array(BackendSrcExemptionsModelsExemptionRead$outboundSchema),
    total: z.number().int(),
    page: z.number().int(),
    size: z.number().int(),
    pages: z.number().int(),
  });

export function fastapiPaginationDefaultPageExemptionRead2ToJSON(
  fastapiPaginationDefaultPageExemptionRead2:
    FastapiPaginationDefaultPageExemptionRead2,
): string {
  return JSON.stringify(
    FastapiPaginationDefaultPageExemptionRead2$outboundSchema.parse(
      fastapiPaginationDefaultPageExemptionRead2,
    ),
  );
}
export function fastapiPaginationDefaultPageExemptionRead2FromJSON(
  jsonString: string,
): SafeParseResult<
  FastapiPaginationDefaultPageExemptionRead2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FastapiPaginationDefaultPageExemptionRead2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FastapiPaginationDefaultPageExemptionRead2' from JSON`,
  );
}
