/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const NexusStateEnum = {
  Exposed: "EXPOSED",
  Approaching: "APPROACHING",
  PendingRegistration: "PENDING_REGISTRATION",
  OssPendingRegistration: "OSS_PENDING_REGISTRATION",
  Registered: "REGISTERED",
  OssRegistered: "OSS_REGISTERED",
  NotExposed: "NOT_EXPOSED",
} as const;
export type NexusStateEnum = ClosedEnum<typeof NexusStateEnum>;

/** @internal */
export const NexusStateEnum$inboundSchema: z.ZodNativeEnum<
  typeof NexusStateEnum
> = z.nativeEnum(NexusStateEnum);
/** @internal */
export const NexusStateEnum$outboundSchema: z.ZodNativeEnum<
  typeof NexusStateEnum
> = NexusStateEnum$inboundSchema;
