/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of OSS registration.
 */
export const OssTypeEnum = {
  Union: "UNION",
  NonUnion: "NON_UNION",
} as const;
/**
 * Type of OSS registration.
 */
export type OssTypeEnum = ClosedEnum<typeof OssTypeEnum>;

/** @internal */
export const OssTypeEnum$inboundSchema: z.ZodNativeEnum<typeof OssTypeEnum> = z
  .nativeEnum(OssTypeEnum);
/** @internal */
export const OssTypeEnum$outboundSchema: z.ZodNativeEnum<typeof OssTypeEnum> =
  OssTypeEnum$inboundSchema;
