/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransactionRead,
  TransactionRead$inboundSchema,
  TransactionRead$Outbound,
  TransactionRead$outboundSchema,
} from "./transactionread.js";

export type PageTransactionRead = {
  items: Array<TransactionRead>;
  total: number;
  page: number;
  size: number;
  pages?: number | undefined;
};

/** @internal */
export const PageTransactionRead$inboundSchema: z.ZodType<
  PageTransactionRead,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(TransactionRead$inboundSchema),
  total: z.number().int(),
  page: z.number().int(),
  size: z.number().int(),
  pages: z.number().int().optional(),
});

/** @internal */
export type PageTransactionRead$Outbound = {
  items: Array<TransactionRead$Outbound>;
  total: number;
  page: number;
  size: number;
  pages?: number | undefined;
};

/** @internal */
export const PageTransactionRead$outboundSchema: z.ZodType<
  PageTransactionRead$Outbound,
  z.ZodTypeDef,
  PageTransactionRead
> = z.object({
  items: z.array(TransactionRead$outboundSchema),
  total: z.number().int(),
  page: z.number().int(),
  size: z.number().int(),
  pages: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageTransactionRead$ {
  /** @deprecated use `PageTransactionRead$inboundSchema` instead. */
  export const inboundSchema = PageTransactionRead$inboundSchema;
  /** @deprecated use `PageTransactionRead$outboundSchema` instead. */
  export const outboundSchema = PageTransactionRead$outboundSchema;
  /** @deprecated use `PageTransactionRead$Outbound` instead. */
  export type Outbound = PageTransactionRead$Outbound;
}

export function pageTransactionReadToJSON(
  pageTransactionRead: PageTransactionRead,
): string {
  return JSON.stringify(
    PageTransactionRead$outboundSchema.parse(pageTransactionRead),
  );
}

export function pageTransactionReadFromJSON(
  jsonString: string,
): SafeParseResult<PageTransactionRead, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageTransactionRead$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageTransactionRead' from JSON`,
  );
}
