/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const PhysicalNexusSource = {
  User: "USER",
  Deel: "DEEL",
} as const;
export type PhysicalNexusSource = ClosedEnum<typeof PhysicalNexusSource>;

/** @internal */
export const PhysicalNexusSource$inboundSchema: z.ZodNativeEnum<
  typeof PhysicalNexusSource
> = z.nativeEnum(PhysicalNexusSource);
/** @internal */
export const PhysicalNexusSource$outboundSchema: z.ZodNativeEnum<
  typeof PhysicalNexusSource
> = PhysicalNexusSource$inboundSchema;
