/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const PhysicalNexusCategory = {
  PhysicalBusinessLocation: "PHYSICAL_BUSINESS_LOCATION",
  TelecommutingOrRemoteEmployee: "TELECOMMUTING_OR_REMOTE_EMPLOYEE",
  WarrantyAndRepairServices: "WARRANTY_AND_REPAIR_SERVICES",
  CatalogueDistributionOrAdvertisingMaterial:
    "CATALOGUE_DISTRIBUTION_OR_ADVERTISING_MATERIAL",
  DeliveryByCommonCarrier: "DELIVERY_BY_COMMON_CARRIER",
  DeliveryByOwnVehicles: "DELIVERY_BY_OWN_VEHICLES",
  InStateSalesPerson: "IN_STATE_SALES_PERSON",
  IndependentContractorOrThirdPartySalesPerson:
    "INDEPENDENT_CONTRACTOR_OR_THIRD_PARTY_SALES_PERSON",
  WarehouseAndInventoryPresence: "WAREHOUSE_AND_INVENTORY_PRESENCE",
  EmployeesAgentsContractors: "EMPLOYEES_AGENTS_CONTRACTORS",
  OwnLeaseAProperty: "OWN_LEASE_A_PROPERTY",
  Inventory: "INVENTORY",
  DeliveryUsingCompanyVehicles: "DELIVERY_USING_COMPANY_VEHICLES",
  OwnBusinessInfrastructureAndEquipment:
    "OWN_BUSINESS_INFRASTRUCTURE_AND_EQUIPMENT",
  OnSiteInstallationMaintenanceServices:
    "ON_SITE_INSTALLATION_MAINTENANCE_SERVICES",
  FrequentParticipationInTradeShowsEvents:
    "FREQUENT_PARTICIPATION_IN_TRADE_SHOWS_EVENTS",
  ManufactureOrProductionInCanada: "MANUFACTURE_OR_PRODUCTION_IN_CANADA",
  PerformingServicesInTheJurisdiction:
    "PERFORMING_SERVICES_IN_THE_JURISDICTION",
  ManufacturingFacilities: "MANUFACTURING_FACILITIES",
  ServersDataCenters: "SERVERS_DATA_CENTERS",
  TradeShowPresence: "TRADE_SHOW_PRESENCE",
  TradeShowPresenceWithoutSales: "TRADE_SHOW_PRESENCE_WITHOUT_SALES",
  DigitalInfrastructureLocalized: "DIGITAL_INFRASTRUCTURE_LOCALIZED",
  PermanentEstablishment: "PERMANENT_ESTABLISHMENT",
  EnterContractsWithLocals: "ENTER_CONTRACTS_WITH_LOCALS",
  ConsignmentStockArrangements: "CONSIGNMENT_STOCK_ARRANGEMENTS",
} as const;
export type PhysicalNexusCategory = ClosedEnum<typeof PhysicalNexusCategory>;

/** @internal */
export const PhysicalNexusCategory$inboundSchema: z.ZodNativeEnum<
  typeof PhysicalNexusCategory
> = z.nativeEnum(PhysicalNexusCategory);
/** @internal */
export const PhysicalNexusCategory$outboundSchema: z.ZodNativeEnum<
  typeof PhysicalNexusCategory
> = PhysicalNexusCategory$inboundSchema;
