/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ProductStatusEnum,
  ProductStatusEnum$inboundSchema,
  ProductStatusEnum$outboundSchema,
} from "./productstatusenum.js";

export type ProductUpdate = {
  /**
   * The unique identifier of the product to be updated.
   */
  id?: string | undefined;
  /**
   * External identifier provided for the product,
   *
   * @remarks
   *         typically by the source system.
   */
  externalId?: string | undefined;
  sku?: Array<string> | undefined;
  /**
   * Name of the product.
   */
  name: string;
  /**
   * Description of the product.
   */
  description?: string | undefined;
  status?: ProductStatusEnum | undefined;
  /**
   * Main category of the product.
   *
   * @remarks
   *     For example, Physical, Digital, etc. You can
   *     retrieve supported categories from this endpoint
   *     /v1/product/categories
   */
  productCategory: string;
  /**
   * Subcategory of the product.
   *
   * @remarks
   *     For example, General Clothing, UNKNOWN, etc. You can
   *     retrieve supported sub-categories from this endpoint
   *     /v1/product/categories
   */
  productSubcategory: string;
  /**
   * Indicates whether the product is tax-exempt.
   */
  taxExempt: boolean;
  /**
   * Indicates if the product classification failed.
   */
  classificationFailed?: boolean | undefined;
};

/** @internal */
export const ProductUpdate$inboundSchema: z.ZodType<
  ProductUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  external_id: z.string().optional(),
  sku: z.array(z.string()).optional(),
  name: z.string(),
  description: z.string().optional(),
  status: ProductStatusEnum$inboundSchema.optional(),
  product_category: z.string(),
  product_subcategory: z.string(),
  tax_exempt: z.boolean(),
  classification_failed: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "external_id": "externalId",
    "product_category": "productCategory",
    "product_subcategory": "productSubcategory",
    "tax_exempt": "taxExempt",
    "classification_failed": "classificationFailed",
  });
});
/** @internal */
export type ProductUpdate$Outbound = {
  id?: string | undefined;
  external_id?: string | undefined;
  sku?: Array<string> | undefined;
  name: string;
  description?: string | undefined;
  status?: string | undefined;
  product_category: string;
  product_subcategory: string;
  tax_exempt: boolean;
  classification_failed: boolean;
};

/** @internal */
export const ProductUpdate$outboundSchema: z.ZodType<
  ProductUpdate$Outbound,
  z.ZodTypeDef,
  ProductUpdate
> = z.object({
  id: z.string().optional(),
  externalId: z.string().optional(),
  sku: z.array(z.string()).optional(),
  name: z.string(),
  description: z.string().optional(),
  status: ProductStatusEnum$outboundSchema.optional(),
  productCategory: z.string(),
  productSubcategory: z.string(),
  taxExempt: z.boolean(),
  classificationFailed: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    externalId: "external_id",
    productCategory: "product_category",
    productSubcategory: "product_subcategory",
    taxExempt: "tax_exempt",
    classificationFailed: "classification_failed",
  });
});

export function productUpdateToJSON(productUpdate: ProductUpdate): string {
  return JSON.stringify(ProductUpdate$outboundSchema.parse(productUpdate));
}
export function productUpdateFromJSON(
  jsonString: string,
): SafeParseResult<ProductUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductUpdate' from JSON`,
  );
}
