/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const RegistrationCategoryEnum = {
  Regular: "REGULAR",
  Imported: "IMPORTED",
  Deregistration: "DEREGISTRATION",
} as const;
export type RegistrationCategoryEnum = ClosedEnum<
  typeof RegistrationCategoryEnum
>;

/** @internal */
export const RegistrationCategoryEnum$inboundSchema: z.ZodNativeEnum<
  typeof RegistrationCategoryEnum
> = z.nativeEnum(RegistrationCategoryEnum);
/** @internal */
export const RegistrationCategoryEnum$outboundSchema: z.ZodNativeEnum<
  typeof RegistrationCategoryEnum
> = RegistrationCategoryEnum$inboundSchema;
