/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const RegistrationsRegimeEnum = {
  Standard: "STANDARD",
  Simplified: "SIMPLIFIED",
} as const;
export type RegistrationsRegimeEnum = ClosedEnum<
  typeof RegistrationsRegimeEnum
>;

/** @internal */
export const RegistrationsRegimeEnum$inboundSchema: z.ZodNativeEnum<
  typeof RegistrationsRegimeEnum
> = z.nativeEnum(RegistrationsRegimeEnum);
/** @internal */
export const RegistrationsRegimeEnum$outboundSchema: z.ZodNativeEnum<
  typeof RegistrationsRegimeEnum
> = RegistrationsRegimeEnum$inboundSchema;
