/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const RelatedEntityType = {
  Exemption: "EXEMPTION",
  Registration: "REGISTRATION",
  Filing: "FILING",
  FilingPayment: "FILING_PAYMENT",
} as const;
export type RelatedEntityType = ClosedEnum<typeof RelatedEntityType>;

/** @internal */
export const RelatedEntityType$inboundSchema: z.ZodNativeEnum<
  typeof RelatedEntityType
> = z.nativeEnum(RelatedEntityType);
/** @internal */
export const RelatedEntityType$outboundSchema: z.ZodNativeEnum<
  typeof RelatedEntityType
> = RelatedEntityType$inboundSchema;
