/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const TaxItemTypeEnum = {
  ImportedOriginal: "IMPORTED_ORIGINAL",
  Imported: "IMPORTED",
  Calculated: "CALCULATED",
} as const;
export type TaxItemTypeEnum = ClosedEnum<typeof TaxItemTypeEnum>;

/** @internal */
export const TaxItemTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof TaxItemTypeEnum
> = z.nativeEnum(TaxItemTypeEnum);
/** @internal */
export const TaxItemTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof TaxItemTypeEnum
> = TaxItemTypeEnum$inboundSchema;
