/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const TaxLiabilitySourceEnum = {
  Calculated: "CALCULATED",
  Collected: "COLLECTED",
} as const;
export type TaxLiabilitySourceEnum = ClosedEnum<typeof TaxLiabilitySourceEnum>;

/** @internal */
export const TaxLiabilitySourceEnum$inboundSchema: z.ZodNativeEnum<
  typeof TaxLiabilitySourceEnum
> = z.nativeEnum(TaxLiabilitySourceEnum);
/** @internal */
export const TaxLiabilitySourceEnum$outboundSchema: z.ZodNativeEnum<
  typeof TaxLiabilitySourceEnum
> = TaxLiabilitySourceEnum$inboundSchema;
