/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AddressStatus,
  AddressStatus$inboundSchema,
  AddressStatus$outboundSchema,
} from "./addressstatus.js";
import {
  AddressType,
  AddressType$inboundSchema,
  AddressType$outboundSchema,
} from "./addresstype.js";
import {
  CountryCodeEnum,
  CountryCodeEnum$inboundSchema,
  CountryCodeEnum$outboundSchema,
} from "./countrycodeenum.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TransactionAddressBuilder = {
  /**
   * Phone number associated with the address.
   */
  phone?: string | undefined;
  /**
   * Primary street address.
   */
  street1?: string | undefined;
  /**
   * Additional street address details, such as an apartment or suite number.
   */
  street2?: string | undefined;
  /**
   * City where the customer resides.
   */
  city?: string | undefined;
  /**
   * County or district of the customer.
   */
  county?: string | undefined;
  /**
   * State or province of the customer.
   */
  state?: string | undefined;
  /**
   * ZIP or Postal code of the customer.
   */
  postalCode?: string | undefined;
  country?: CountryCodeEnum | undefined;
  /**
   * Complete address string of the customer, which can be used as an alternative to individual fields.
   */
  fullAddress?: string | undefined;
  type: AddressType;
  /**
   * Optional additional enriched data for the address.
   */
  enrichedFields?: string | undefined;
  status?: AddressStatus | undefined;
  organizationId?: string | undefined;
};

/** @internal */
export const TransactionAddressBuilder$inboundSchema: z.ZodType<
  TransactionAddressBuilder,
  z.ZodTypeDef,
  unknown
> = z.object({
  phone: z.string().optional(),
  street_1: z.string().optional(),
  street_2: z.string().optional(),
  city: z.string().optional(),
  county: z.string().optional(),
  state: z.string().optional(),
  postal_code: z.string().optional(),
  country: CountryCodeEnum$inboundSchema.optional(),
  full_address: z.string().optional(),
  type: AddressType$inboundSchema,
  enriched_fields: z.string().optional(),
  status: AddressStatus$inboundSchema.optional(),
  organization_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "street_1": "street1",
    "street_2": "street2",
    "postal_code": "postalCode",
    "full_address": "fullAddress",
    "enriched_fields": "enrichedFields",
    "organization_id": "organizationId",
  });
});

/** @internal */
export type TransactionAddressBuilder$Outbound = {
  phone?: string | undefined;
  street_1?: string | undefined;
  street_2?: string | undefined;
  city?: string | undefined;
  county?: string | undefined;
  state?: string | undefined;
  postal_code?: string | undefined;
  country?: string | undefined;
  full_address?: string | undefined;
  type: string;
  enriched_fields?: string | undefined;
  status?: string | undefined;
  organization_id?: string | undefined;
};

/** @internal */
export const TransactionAddressBuilder$outboundSchema: z.ZodType<
  TransactionAddressBuilder$Outbound,
  z.ZodTypeDef,
  TransactionAddressBuilder
> = z.object({
  phone: z.string().optional(),
  street1: z.string().optional(),
  street2: z.string().optional(),
  city: z.string().optional(),
  county: z.string().optional(),
  state: z.string().optional(),
  postalCode: z.string().optional(),
  country: CountryCodeEnum$outboundSchema.optional(),
  fullAddress: z.string().optional(),
  type: AddressType$outboundSchema,
  enrichedFields: z.string().optional(),
  status: AddressStatus$outboundSchema.optional(),
  organizationId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    street1: "street_1",
    street2: "street_2",
    postalCode: "postal_code",
    fullAddress: "full_address",
    enrichedFields: "enriched_fields",
    organizationId: "organization_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionAddressBuilder$ {
  /** @deprecated use `TransactionAddressBuilder$inboundSchema` instead. */
  export const inboundSchema = TransactionAddressBuilder$inboundSchema;
  /** @deprecated use `TransactionAddressBuilder$outboundSchema` instead. */
  export const outboundSchema = TransactionAddressBuilder$outboundSchema;
  /** @deprecated use `TransactionAddressBuilder$Outbound` instead. */
  export type Outbound = TransactionAddressBuilder$Outbound;
}

export function transactionAddressBuilderToJSON(
  transactionAddressBuilder: TransactionAddressBuilder,
): string {
  return JSON.stringify(
    TransactionAddressBuilder$outboundSchema.parse(transactionAddressBuilder),
  );
}

export function transactionAddressBuilderFromJSON(
  jsonString: string,
): SafeParseResult<TransactionAddressBuilder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionAddressBuilder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionAddressBuilder' from JSON`,
  );
}
